import type { ToolsCatalog } from './types';

export const toolsFixture: ToolsCatalog = {
  schema_version: 1,
  game_build_id: 'steam:24575825',
  mapping_sha256: 'fixture',
  verified: true,
  model_notice: 'exact 입력 기반 비교 모델',
  work_names_ko: { Handcraft: '수작업', Mining: '채굴' },
  breeding: {
    contract_review_id: 'fixture:breeding',
    general_formula: 'fixture exact formula',
    species: [
      {
        internal_id: 'Anubis',
        name_ko: '아누비스',
        name_en: 'Anubis',
        paldex_number: 100,
        paldex_suffix: '',
        combi_rank: 1000,
        combi_duplicate_priority: 100000,
        ignore_combi: false,
        source_row_id: 'Anubis',
      },
      {
        internal_id: 'NightWorker',
        name_ko: '야간 작업팰',
        name_en: 'Night Worker',
        paldex_number: 101,
        paldex_suffix: '',
        combi_rank: 2000,
        combi_duplicate_priority: 200000,
        ignore_combi: false,
        source_row_id: 'NightWorker',
      },
      {
        internal_id: 'FastMount',
        name_ko: '빠른 탈것',
        name_en: 'Fast Mount',
        paldex_number: 102,
        paldex_suffix: '',
        combi_rank: 3000,
        combi_duplicate_priority: 300000,
        ignore_combi: false,
        source_row_id: 'FastMount',
      },
    ],
    special_rules: [
      {
        rule_id: 'special:fixture',
        parent_a_internal_id: 'Anubis',
        parent_a_gender: 'None',
        parent_b_internal_id: 'NightWorker',
        parent_b_gender: 'None',
        child_internal_id: 'FastMount',
        source_row_ids: ['fixture'],
      },
    ],
  },
  pals: [
    {
      id: 'Anubis',
      name_ko: '아누비스',
      image_path: null,
      paldex_number: 100,
      hp: 120,
      attack: 130,
      defense: 100,
      run_speed: 800,
      ride_sprint_speed: 0,
      stamina: 100,
      food_amount: 6,
      nocturnal: false,
      work_suitability: [{ id: 'Handcraft', name_ko: '수작업', level: 4 }],
    },
    {
      id: 'NightWorker',
      name_ko: '야간 작업팰',
      image_path: null,
      paldex_number: 101,
      hp: 90,
      attack: 80,
      defense: 80,
      run_speed: 600,
      ride_sprint_speed: 900,
      stamina: 120,
      food_amount: 3,
      nocturnal: true,
      work_suitability: [{ id: 'Mining', name_ko: '채굴', level: 3 }],
    },
    {
      id: 'FastMount',
      name_ko: '빠른 탈것',
      image_path: null,
      paldex_number: 102,
      hp: 80,
      attack: 70,
      defense: 70,
      run_speed: 1000,
      ride_sprint_speed: 1600,
      stamina: 140,
      food_amount: 5,
      nocturnal: false,
      work_suitability: [],
    },
  ],
  buildings: [
    {
      id: 'BreedFarm',
      name_ko: '배합 목장',
      category: 'Pal',
      materials: [
        { item_id: 'Wood', name_ko: '목재', quantity: 100 },
        { item_id: 'Stone', name_ko: '돌', quantity: 20 },
      ],
    },
  ],
};
