import type { MapBundle, MapTileIndex } from './types';

const index = (mapId: string, regionId: string): MapTileIndex => ({
  schema_version: 2,
  game_build_id: '24575825',
  map_id: mapId,
  region_id: regionId,
  map_width_px: 2048,
  map_height_px: 2048,
  tile_count: 21,
  tiles: Array.from({ length: 16 }, (_, position) => {
    const x = position % 4;
    const y = Math.floor(position / 4);
    return {
      level: 0,
      x,
      y,
      relative_path: `regions/${mapId}/tiles/0/${String(y)}_${String(x)}.jpg`,
      size_bytes: 100,
      sha256: String(position).padStart(64, '0'),
      map_rect: { min_x: x * 512, min_y: y * 512, max_x: (x + 1) * 512, max_y: (y + 1) * 512 },
    };
  }),
});

export const mapFixture: MapBundle = {
  indexes: [index('MainMap', 'FirstRegion'), index('Tree', 'DummyRegion')],
  exact: {
    schema_version: 1,
    game_build_id: 'steam:24575825',
    poi_count: 4,
    pois: [
      {
        id: 'boss:raibao',
        kind: 'boss',
        display_name: '라이바오',
        entity_id: 'GrassPanda_Electric',
        map_id: 'MainMap',
        region_id: 'FirstRegion',
        world_x: -206970,
        world_y: 363810,
        map_x: 1538,
        map_y: 786,
        source_build_id: '24575825',
        verified: true,
      },
      {
        id: 'fast:01',
        kind: 'fast_travel',
        display_name: '시작의 대지',
        entity_id: 'FT_001',
        map_id: 'MainMap',
        region_id: 'FirstRegion',
        world_x: 100,
        world_y: 200,
        map_x: 900,
        map_y: 1120,
        source_build_id: '24575825',
        verified: true,
      },
      {
        id: 'dungeon:01',
        kind: 'dungeon',
        display_name: '던전 입구',
        entity_id: 'Dungeon_001',
        map_id: 'MainMap',
        region_id: 'FirstRegion',
        world_x: 300,
        world_y: 400,
        map_x: 1100,
        map_y: 980,
        source_build_id: '24575825',
        verified: true,
      },
      {
        id: 'wanted:01',
        kind: 'wanted',
        display_name: '현상범 에고',
        entity_id: 'Bounty_001',
        map_id: 'Tree',
        region_id: 'DummyRegion',
        world_x: 500,
        world_y: 600,
        map_x: 720,
        map_y: 640,
        source_build_id: '24575825',
        verified: true,
      },
    ],
  },
  terminology: {
    schema_version: 1,
    language: 'ko',
    game_build_id: '24575825',
    groups: [
      { id: 'location', label_ko: '위치', description_ko: '탐험 위치' },
      { id: 'enemy', label_ko: '적', description_ko: '전투 위치' },
      { id: 'collectible', label_ko: '수집품', description_ko: '수집 위치' },
      { id: 'npc', label_ko: '등장인물', description_ko: '등장인물 위치' },
      { id: 'resource', label_ko: '자원', description_ko: '자원 위치' },
    ],
    terms: [
      {
        id: 'fast_travel',
        group_id: 'location',
        label_ko: '참수리 상',
        generic_title_ko: '참수리 상',
        description_ko: '순간이동 지점입니다.',
        aliases_ko: ['빠른 이동', '워프'],
        verification: 'reviewed',
      },
      {
        id: 'boss',
        group_id: 'enemy',
        label_ko: '필드 보스',
        generic_title_ko: '필드 보스 출현 지점',
        description_ko: '강한 팰의 출현 지점입니다.',
        aliases_ko: ['보스', '알파 팰'],
        verification: 'reviewed',
      },
      {
        id: 'dungeon',
        group_id: 'location',
        label_ko: '던전',
        generic_title_ko: '던전 입구',
        description_ko: '던전 입구입니다.',
        aliases_ko: ['동굴'],
        verification: 'reviewed',
      },
      {
        id: 'wanted',
        group_id: 'enemy',
        label_ko: '지명수배',
        generic_title_ko: '지명수배 대상',
        description_ko: '현상범 위치입니다.',
        aliases_ko: ['현상범'],
        verification: 'reviewed',
      },
      {
        id: 'tower',
        group_id: 'enemy',
        label_ko: '보스 타워',
        generic_title_ko: '보스 타워 입구',
        description_ko: '보스 타워 입구입니다.',
        aliases_ko: [],
        verification: 'reviewed',
      },
      {
        id: 'sealed-realm',
        group_id: 'enemy',
        label_ko: '봉인된 영역',
        generic_title_ko: '봉인된 영역',
        description_ko: '필드 보스 위치에 합쳐 표시합니다.',
        aliases_ko: [],
        verification: 'needs_game_l10n_review',
        filter_visibility: 'merged',
        merged_into: 'boss',
      },
      {
        id: 'egg',
        group_id: 'collectible',
        label_ko: '팰의 알',
        generic_title_ko: '팰의 알',
        description_ko: '팰의 알 위치입니다.',
        aliases_ko: ['알'],
        verification: 'reviewed',
      },
      {
        id: 'ore-quartz',
        group_id: 'resource',
        label_ko: '순수한 석영',
        generic_title_ko: '순수한 석영 광맥',
        description_ko: '순수한 석영 광맥입니다.',
        aliases_ko: ['석영'],
        verification: 'reviewed',
      },
      {
        id: 'ancient-shrine',
        group_id: 'collectible',
        label_ko: '고대 유적',
        generic_title_ko: '고대 유적',
        description_ko: '검토 중인 위치입니다.',
        aliases_ko: [],
        verification: 'needs_game_l10n_review',
        filter_visibility: 'hidden_until_verified',
      },
    ],
  },
  supplemental: {
    schema_version: 2,
    game_build_id: '24575825',
    provenance: {
      source_name: 'PalMods + PalDB map data',
      source_page: 'https://example.invalid',
      exact_local_build_verified: false,
    },
    layers: [
      {
        index: 0,
        id: 'tower',
        label: 'Tower',
        group: 'navigation',
        default_enabled: true,
        minimum_scale: 0.2,
        dense: false,
        point_count: 1,
      },
      {
        index: 1,
        id: 'sealed-realm',
        label: 'Sealed Realm',
        group: 'enemy',
        default_enabled: false,
        minimum_scale: 0.2,
        dense: false,
        point_count: 1,
      },
      {
        index: 2,
        id: 'ore-quartz',
        label: 'Quartz',
        group: 'resource',
        default_enabled: false,
        minimum_scale: 0.4,
        dense: true,
        point_count: 2,
      },
      {
        index: 3,
        id: 'ancient-shrine',
        label: 'Ancient Shrine',
        group: 'collectible',
        default_enabled: false,
        minimum_scale: 0.4,
        dense: true,
        point_count: 1,
      },
      {
        index: 4,
        id: 'egg',
        label: 'Egg',
        group: 'collectible',
        default_enabled: false,
        minimum_scale: 0.4,
        dense: true,
        point_count: 1,
      },
    ],
    regions: [
      {
        map_id: 'MainMap',
        region_id: 'FirstRegion',
        point_count: 5,
        points: [
          [0, 0, 0, 1024, 1024],
          [1, 0, 0, 1300, 820],
          [2, 0, 0, 600, 600],
          [2, 0, 0, 640, 640],
          [3, 0, 0, 800, 800],
        ],
      },
      {
        map_id: 'Tree',
        region_id: 'DummyRegion',
        point_count: 1,
        points: [[4, 0, 0, 900, 900]],
      },
    ],
  },
};
