#Requires -Version 5.1

[CmdletBinding()]
param(
    [string]$ItemsCatalog = (
        Join-Path $PSScriptRoot (
            '..\..\assets\palbeacon\game\catalog\items.v1.json'
        )
    ),
    [string]$WorldCatalog = (
        Join-Path $PSScriptRoot (
            '..\..\assets\palbeacon\game\catalog\world.v1.json'
        )
    ),
    [Parameter(Mandatory)]
    [string]$OutputDirectory,
    [string]$DatasetVersion = 'public-meta-steam-24575825-v1',
    [string]$GameVersion = 'steam-build-24575825',
    [string]$GameBuildId = 'steam:24575825',
    [ValidateRange(25, 1000)]
    [int]$ChunkSize = 400
)

$ErrorActionPreference = 'Stop'
$compilerVersion = 'pal-public-metadata-compiler-v1'
$schemaVersion = 'public-knowledge-graph-v1'
$utf8NoBom = New-Object Text.UTF8Encoding $false

function ConvertTo-SqlText {
    param([AllowEmptyString()][string]$Value)

    $escaped = $Value.Replace("'", "''")
    return "'$escaped'"
}

function ConvertTo-CompactJson {
    param([Parameter(Mandatory)][AllowEmptyCollection()][object]$Value)

    return ConvertTo-Json -InputObject $Value -Depth 30 -Compress
}

function Get-TextSha256 {
    param([Parameter(Mandatory)][AllowEmptyString()][string]$Value)

    $sha = [Security.Cryptography.SHA256]::Create()
    try {
        $bytes = [Text.Encoding]::UTF8.GetBytes($Value)
        return (
            [BitConverter]::ToString($sha.ComputeHash($bytes)).
                Replace('-', '').
                ToLowerInvariant()
        )
    }
    finally {
        $sha.Dispose()
    }
}

function Get-FileSha256 {
    param([Parameter(Mandatory)][string]$Path)

    return (Get-FileHash -Algorithm SHA256 -LiteralPath $Path).
        Hash.ToLowerInvariant()
}

function Assert-InternalId {
    param(
        [Parameter(Mandatory)][string]$Value,
        [Parameter(Mandatory)][string]$Kind
    )

    if (
        $Value.Length -gt 220 -or
        $Value -notmatch '^[A-Za-z0-9_.:-]+$'
    ) {
        throw "$Kind contains an unsupported internal identifier: $Value"
    }
}

function Write-Utf8File {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][AllowEmptyString()][string]$Content
    )

    [IO.File]::WriteAllText($Path, $Content, $utf8NoBom)
}

function New-SqlDocument {
    param([Parameter(Mandatory)][string[]]$Statements)

    return (
        "-- Generated by $compilerVersion. Do not edit.`n" +
        "PRAGMA foreign_keys=ON;`n" +
        ($Statements -join "`n") +
        "`n"
    )
}

function Write-SqlChunks {
    param(
        [Parameter(Mandatory)][string]$Prefix,
        [Parameter(Mandatory)][AllowEmptyCollection()]
        [Collections.Generic.List[string]]$Statements,
        [Parameter(Mandatory)][ValidateRange(1, 100)]
        [int]$BaseRowsPerStatement
    )

    $paths = New-Object Collections.Generic.List[string]
    for ($offset = 0; $offset -lt $Statements.Count; $offset += $ChunkSize) {
        $last = [Math]::Min($offset + $ChunkSize - 1, $Statements.Count - 1)
        $chunk = @($Statements[$offset..$last])
        $index = [int]($offset / $ChunkSize)
        $name = '{0}_{1:D4}.sql' -f $Prefix, $index
        Write-SeedSqlFile `
            -Name $name `
            -Statements $chunk `
            -BaseRowsWrittenUpperBound (
                $chunk.Count * $BaseRowsPerStatement
            )
        $paths.Add($name)
    }
    return @($paths | ForEach-Object { $_ })
}

function Write-SeedSqlFile {
    param(
        [Parameter(Mandatory)][string]$Name,
        [Parameter(Mandatory)][string[]]$Statements,
        [Parameter(Mandatory)][ValidateRange(0, [long]::MaxValue)]
        [long]$BaseRowsWrittenUpperBound
    )

    $applyOrder = $writtenSql.Count
    $payloadDocument = New-SqlDocument $Statements
    $payloadSha256 = Get-TextSha256 $payloadDocument
    # The checkpoint row and its dataset/time index add two more D1 writes.
    $baseRowsWithCheckpoint = $BaseRowsWrittenUpperBound + 2
    $conservativeRowsWritten = [long][Math]::Ceiling(
        $baseRowsWithCheckpoint * 3.0
    )
    $checkpointInput = ConvertTo-CompactJson ([ordered]@{
        path = $Name
        payload_sha256 = $payloadSha256
        apply_order = $applyOrder
    })
    $checkpointOutput = ConvertTo-CompactJson ([ordered]@{
        base_rows_written_upper_bound = $baseRowsWithCheckpoint
        conservative_rows_written = $conservativeRowsWritten
    })
    $checkpointRunId = (
        "seed-checkpoint:${DatasetVersion}:{0:D4}" -f $applyOrder
    )
    $checkpointStatement = (
        "INSERT INTO knowledge_pipeline_runs " +
        "(run_id, dataset_version, pipeline_name, compiler_version, status, " +
        "input_facets_json, output_facets_json, completed_at) VALUES (" +
        "$(ConvertTo-SqlText $checkpointRunId), " +
        "$(ConvertTo-SqlText $DatasetVersion), " +
        "'public-metadata-seed-checkpoint-v1', " +
        "$(ConvertTo-SqlText $compilerVersion), 'completed', " +
        "$(ConvertTo-SqlText $checkpointInput), " +
        "$(ConvertTo-SqlText $checkpointOutput), CURRENT_TIMESTAMP);"
    )
    $path = Join-Path $resolvedOutput $Name
    Write-Utf8File `
        -Path $path `
        -Content (New-SqlDocument @($Statements + $checkpointStatement))
    $writtenSql.Add($Name)
    $sqlFileRecords.Add([pscustomobject][ordered]@{
        path = $Name
        payload_sha256 = $payloadSha256
        base_rows_written_upper_bound = $baseRowsWithCheckpoint
        conservative_rows_written = $conservativeRowsWritten
        apply_order = $applyOrder
    })
}

$resolvedItems = [IO.Path]::GetFullPath($ItemsCatalog)
$resolvedWorld = [IO.Path]::GetFullPath($WorldCatalog)
$resolvedOutput = [IO.Path]::GetFullPath($OutputDirectory)

foreach ($catalogPath in @($resolvedItems, $resolvedWorld)) {
    if (-not (Test-Path -LiteralPath $catalogPath -PathType Leaf)) {
        throw "Required exact-Build catalog does not exist: $catalogPath"
    }
}
if (Test-Path -LiteralPath $resolvedOutput) {
    throw "Output directory already exists; refusing to overwrite: $resolvedOutput"
}
if ($DatasetVersion -notmatch '^[A-Za-z0-9_.:-]+$') {
    throw 'DatasetVersion must be an ASCII internal identifier.'
}

$itemsDocument = Get-Content -Raw -Encoding UTF8 -LiteralPath $resolvedItems |
    ConvertFrom-Json
$worldDocument = Get-Content -Raw -Encoding UTF8 -LiteralPath $resolvedWorld |
    ConvertFrom-Json
foreach ($document in @($itemsDocument, $worldDocument)) {
    if ($document.verified -ne $true) {
        throw 'Public metadata may be compiled only from a verified catalog.'
    }
    if ([string]$document.game_build_id -ne $GameBuildId) {
        throw (
            "Catalog game_build_id '$($document.game_build_id)' does not " +
            "match requested '$GameBuildId'."
        )
    }
}
if (
    [string]$itemsDocument.mapping_sha256 -ne
    [string]$worldDocument.mapping_sha256
) {
    throw 'Item and world catalogs do not share the same mapping SHA-256.'
}

$itemModels = New-Object Collections.Generic.List[object]
$itemById = New-Object (
    'Collections.Generic.Dictionary[string,object]'
) ([StringComparer]::Ordinal)
foreach (
    $item in @(
        $itemsDocument.items |
            Sort-Object { [string]$_.item_id }
    )
) {
    if (
        $item.legal_in_game -ne $true -or
        $item.localization_fallback -eq $true -or
        [string]::IsNullOrWhiteSpace([string]$item.name_ko)
    ) {
        continue
    }
    $id = [string]$item.item_id
    Assert-InternalId -Value $id -Kind 'Item'
    if ($itemById.ContainsKey($id)) {
        throw "Duplicate item identifier: $id"
    }
    $model = [pscustomobject][ordered]@{
        Id = $id
        Name = ([string]$item.name_ko).Trim()
        Rarity = [int64]$item.rarity
        Rank = [int64]$item.rank
        Stack = [int64]$item.maximum_stack_count
        WeightMilli = [int64]$item.weight_milli
    }
    $itemModels.Add($model)
    $itemById.Add($id, $model)
}

# Exact game localization intentionally gives rarity variants the same visible
# name. Add a Korean, numeric rarity suffix only when that name is ambiguous so
# the public Wiki never renders indistinguishable cards or relation chips.
foreach (
    $duplicateNameGroup in @(
        $itemModels |
            Group-Object Name |
            Where-Object { $_.Count -gt 1 }
    )
) {
    foreach ($item in $duplicateNameGroup.Group) {
        $item.Name = "$($item.Name) · 희귀도 $($item.Rarity)"
    }
}

$recipeModels = New-Object Collections.Generic.List[object]
$recipeById = New-Object (
    'Collections.Generic.Dictionary[string,object]'
) ([StringComparer]::Ordinal)
foreach (
    $recipe in @(
        $itemsDocument.recipes |
            Sort-Object { [string]$_.recipe_id }
    )
) {
    $recipeId = [string]$recipe.recipe_id
    $outputId = [string]$recipe.output_item_id
    if (-not $itemById.ContainsKey($outputId)) {
        continue
    }
    Assert-InternalId -Value $recipeId -Kind 'Recipe'
    if ($recipeById.ContainsKey($recipeId)) {
        throw "Duplicate recipe identifier: $recipeId"
    }
    $ingredients = New-Object Collections.Generic.List[object]
    $complete = $true
    foreach ($ingredient in @($recipe.ingredients)) {
        $ingredientId = [string]$ingredient.item_id
        if (-not $itemById.ContainsKey($ingredientId)) {
            $complete = $false
            break
        }
        $ingredients.Add([pscustomobject][ordered]@{
            ItemId = $ingredientId
            Name = $itemById[$ingredientId].Name
            Quantity = [int64]$ingredient.quantity
        })
    }
    if (-not $complete -or $ingredients.Count -eq 0) {
        continue
    }
    $output = $itemById[$outputId]
    $model = [pscustomobject][ordered]@{
        Id = $recipeId
        Name = "$($output.Name) 제작법"
        OutputId = $outputId
        OutputName = $output.Name
        OutputQuantity = [int64]$recipe.output_quantity
        WorkAmount = [int64]$recipe.work_amount
        Ingredients = @($ingredients | ForEach-Object { $_ })
    }
    $recipeModels.Add($model)
    $recipeById.Add($recipeId, $model)
}

$technologyModels = New-Object Collections.Generic.List[object]
$technologyById = New-Object (
    'Collections.Generic.Dictionary[string,object]'
) ([StringComparer]::Ordinal)
foreach (
    $technology in @(
        $worldDocument.technologies |
            Sort-Object { [string]$_.technology_id }
    )
) {
    if (
        $technology.localization_fallback -eq $true -or
        [string]::IsNullOrWhiteSpace([string]$technology.name_ko)
    ) {
        continue
    }
    $id = [string]$technology.technology_id
    Assert-InternalId -Value $id -Kind 'Technology'
    if ($technologyById.ContainsKey($id)) {
        throw "Duplicate technology identifier: $id"
    }
    $unlockItems = @(
        @($technology.unlock_item_ids) |
            ForEach-Object { [string]$_ } |
            Where-Object { $itemById.ContainsKey($_) } |
            Sort-Object -Unique
    )
    $unlockRecipes = @(
        @($technology.unlock_recipe_ids) |
            ForEach-Object { [string]$_ } |
            Where-Object { $recipeById.ContainsKey($_) } |
            Sort-Object -Unique
    )
    $model = [pscustomobject][ordered]@{
        Id = $id
        Name = ([string]$technology.name_ko).Trim()
        Level = [int64]$technology.level
        Cost = [int64]$technology.cost
        IsBoss = [bool]$technology.is_boss_technology
        RequiredTechnologyId = [string]$technology.required_technology_id
        UnlockItemIds = $unlockItems
        UnlockRecipeIds = $unlockRecipes
    }
    $technologyModels.Add($model)
    $technologyById.Add($id, $model)
}

$sourceArtifacts = @(
    [ordered]@{
        artifact_id = 'items-v1'
        artifact_kind = 'catalog'
        logical_source_ref = 'exact-build:items.v1.json'
        sha256 = Get-FileSha256 $resolvedItems
        byte_size = (Get-Item -LiteralPath $resolvedItems).Length
        evidence_quality = 'exact'
    },
    [ordered]@{
        artifact_id = 'world-v1'
        artifact_kind = 'catalog'
        logical_source_ref = 'exact-build:world.v1.json'
        sha256 = Get-FileSha256 $resolvedWorld
        byte_size = (Get-Item -LiteralPath $resolvedWorld).Length
        evidence_quality = 'exact'
    }
)

$relationEdgeCount = 0
foreach ($recipe in $recipeModels) {
    $relationEdgeCount += 1 + $recipe.Ingredients.Count
}
foreach ($technology in $technologyModels) {
    $relationEdgeCount += $technology.UnlockItemIds.Count
    $relationEdgeCount += $technology.UnlockRecipeIds.Count
    if (
        -not [string]::IsNullOrWhiteSpace($technology.RequiredTechnologyId) -and
        $technologyById.ContainsKey($technology.RequiredTechnologyId)
    ) {
        $relationEdgeCount++
    }
}
$pageCount = (
    $itemModels.Count + $recipeModels.Count + $technologyModels.Count
)
$entityNodeCount = $pageCount
$graphNodeCount = $entityNodeCount + $pageCount
$graphEdgeCount = $relationEdgeCount + $pageCount

$projectionIdentity = [ordered]@{
    schema = 'pal-public-knowledge-projection-v1'
    compiler_version = $compilerVersion
    dataset_version = $DatasetVersion
    game_build_id = $GameBuildId
    mapping_sha256 = [string]$itemsDocument.mapping_sha256
    policy = [ordered]@{
        dataset_scope = 'public_metadata'
        game_artwork = 'excluded'
        game_descriptions = 'excluded'
        exact_korean_names = 'included'
        structural_numeric_fields = 'included'
    }
    source_artifacts = $sourceArtifacts
    counts = [ordered]@{
        items = $itemModels.Count
        recipes = $recipeModels.Count
        technologies = $technologyModels.Count
        graph_nodes = $graphNodeCount
        graph_edges = $graphEdgeCount
        wiki_pages = $pageCount
    }
}
$projectionSha256 = Get-TextSha256 (
    ConvertTo-CompactJson $projectionIdentity
)

$datasetSql = ConvertTo-SqlText $DatasetVersion
$manifestSql = ConvertTo-SqlText $projectionSha256
$buildEvidence = "game-files:$GameBuildId"
$nodeStatements = New-Object Collections.Generic.List[string]
$edgeStatements = New-Object Collections.Generic.List[string]
$pageStatements = New-Object Collections.Generic.List[string]
$claimStatements = New-Object Collections.Generic.List[string]
$revisionStatements = New-Object Collections.Generic.List[string]
$nodeIds = New-Object (
    'Collections.Generic.HashSet[string]'
) ([StringComparer]::Ordinal)
$pageIds = New-Object (
    'Collections.Generic.HashSet[string]'
) ([StringComparer]::Ordinal)

function Add-GraphNode {
    param(
        [Parameter(Mandatory)][string]$NodeId,
        [Parameter(Mandatory)][string]$NodeKind,
        [Parameter(Mandatory)][string]$Label,
        [Parameter(Mandatory)][string]$SourceRef,
        [Parameter(Mandatory)][object]$HashInput
    )

    Assert-InternalId -Value $NodeId -Kind 'Graph node'
    if (-not $nodeIds.Add($NodeId)) {
        throw "Duplicate graph node: $NodeId"
    }
    $evidenceJson = ConvertTo-CompactJson @($SourceRef, $buildEvidence)
    $contentHash = Get-TextSha256 (ConvertTo-CompactJson $HashInput)
    $nodeStatements.Add(
        "INSERT INTO knowledge_graph_nodes " +
        "(dataset_version, node_id, node_kind, label_ko, evidence_quality, " +
        "evidence_refs_json, content_hash) VALUES (" +
        "$datasetSql, $(ConvertTo-SqlText $NodeId), " +
        "$(ConvertTo-SqlText $NodeKind), $(ConvertTo-SqlText $Label), " +
        "'exact', $(ConvertTo-SqlText $evidenceJson), " +
        "$(ConvertTo-SqlText $contentHash));"
    )
}

function Add-GraphEdge {
    param(
        [Parameter(Mandatory)][string]$EdgeId,
        [Parameter(Mandatory)][string]$FromNodeId,
        [Parameter(Mandatory)][string]$ToNodeId,
        [Parameter(Mandatory)][string]$RelationKind,
        [Parameter(Mandatory)][object]$Attributes,
        [Parameter(Mandatory)][string]$SourceRef
    )

    if (
        -not $nodeIds.Contains($FromNodeId) -or
        -not $nodeIds.Contains($ToNodeId)
    ) {
        throw "Graph edge $EdgeId references a missing endpoint."
    }
    $evidenceJson = ConvertTo-CompactJson @($SourceRef, $buildEvidence)
    $attributesJson = ConvertTo-CompactJson $Attributes
    $contentHash = Get-TextSha256 (
        ConvertTo-CompactJson ([ordered]@{
            edge_id = $EdgeId
            from = $FromNodeId
            to = $ToNodeId
            relation = $RelationKind
            attributes = $Attributes
        })
    )
    $edgeStatements.Add(
        "INSERT INTO knowledge_graph_edges " +
        "(dataset_version, edge_id, from_node_id, to_node_id, relation_kind, " +
        "origin, evidence_quality, evidence_refs_json, attributes_json, " +
        "content_hash) VALUES (" +
        "$datasetSql, $(ConvertTo-SqlText $EdgeId), " +
        "$(ConvertTo-SqlText $FromNodeId), $(ConvertTo-SqlText $ToNodeId), " +
        "$(ConvertTo-SqlText $RelationKind), 'exact_extract', 'exact', " +
        "$(ConvertTo-SqlText $evidenceJson), " +
        "$(ConvertTo-SqlText $attributesJson), " +
        "$(ConvertTo-SqlText $contentHash));"
    )
}

function Add-WikiPage {
    param(
        [Parameter(Mandatory)][string]$EntityNodeId,
        [Parameter(Mandatory)][string]$PageKind,
        [Parameter(Mandatory)][string]$Title,
        [Parameter(Mandatory)][string]$Summary,
        [Parameter(Mandatory)][string]$Body,
        [Parameter(Mandatory)][string]$Claim,
        [Parameter(Mandatory)][string]$SourceRef
    )

    $pageId = "wiki:$EntityNodeId"
    Assert-InternalId -Value $pageId -Kind 'Wiki page'
    if (-not $pageIds.Add($pageId)) {
        throw "Duplicate Wiki page: $pageId"
    }
    $relatedJson = ConvertTo-CompactJson @($EntityNodeId)
    $evidenceJson = ConvertTo-CompactJson @($SourceRef, $buildEvidence)
    $claimId = "claim:$EntityNodeId"
    $pageNodeId = "wiki-page:$EntityNodeId"

    Add-GraphNode `
        -NodeId $pageNodeId `
        -NodeKind 'wiki_page' `
        -Label $Title `
        -SourceRef "wiki-policy:$compilerVersion" `
        -HashInput ([ordered]@{
            page_id = $pageId
            title = $Title
            summary = $Summary
            body = $Body
        })
    Add-GraphEdge `
        -EdgeId "wiki-reference:$EntityNodeId" `
        -FromNodeId $pageNodeId `
        -ToNodeId $EntityNodeId `
        -RelationKind 'references' `
        -Attributes ([ordered]@{}) `
        -SourceRef "wiki-claim:$claimId"

    $pageStatements.Add(
        "INSERT INTO knowledge_wiki_pages " +
        "(dataset_version, page_id, page_kind, title_ko, summary_ko, " +
        "body_markdown, related_node_ids_json, source_manifest_sha256, " +
        "review_status) VALUES (" +
        "$datasetSql, $(ConvertTo-SqlText $pageId), " +
        "$(ConvertTo-SqlText $PageKind), $(ConvertTo-SqlText $Title), " +
        "$(ConvertTo-SqlText $Summary), $(ConvertTo-SqlText $Body), " +
        "$(ConvertTo-SqlText $relatedJson), $manifestSql, 'reviewed');"
    )
    $claimStatements.Add(
        "INSERT INTO knowledge_wiki_claims " +
        "(dataset_version, page_id, claim_id, claim_text_ko, " +
        "evidence_quality, evidence_refs_json, related_node_ids_json) VALUES (" +
        "$datasetSql, $(ConvertTo-SqlText $pageId), " +
        "$(ConvertTo-SqlText $claimId), $(ConvertTo-SqlText $Claim), " +
        "'exact', $(ConvertTo-SqlText $evidenceJson), " +
        "$(ConvertTo-SqlText $relatedJson));"
    )
    $claimsJson = ConvertTo-CompactJson @(
        [ordered]@{
            claim_id = $claimId
            text_ko = $Claim
            quality = 'exact'
            evidence_refs = @($SourceRef, $buildEvidence)
            related_node_ids = @($EntityNodeId)
        }
    )
    $revisionStatements.Add(
        "INSERT INTO knowledge_wiki_revisions " +
        "(dataset_version, page_id, revision_number, title_ko, summary_ko, " +
        "body_markdown, claims_json, related_node_ids_json, change_origin, " +
        "review_status, generator_id, reviewer_id, change_summary_ko) VALUES (" +
        "$datasetSql, $(ConvertTo-SqlText $pageId), 1, " +
        "$(ConvertTo-SqlText $Title), $(ConvertTo-SqlText $Summary), " +
        "$(ConvertTo-SqlText $Body), $(ConvertTo-SqlText $claimsJson), " +
        "$(ConvertTo-SqlText $relatedJson), 'exact_compiler', 'reviewed', " +
        "$(ConvertTo-SqlText $compilerVersion), 'public-metadata-policy-v1', " +
        "'공개 허용 구조 데이터로 최초 컴파일');"
    )
}

foreach ($item in $itemModels) {
    $nodeId = "item:$($item.Id)"
    Add-GraphNode `
        -NodeId $nodeId `
        -NodeKind 'item' `
        -Label $item.Name `
        -SourceRef "exact-build:items.v1.json:item:$($item.Id)" `
        -HashInput $item
}
foreach ($recipe in $recipeModels) {
    $nodeId = "recipe:$($recipe.Id)"
    Add-GraphNode `
        -NodeId $nodeId `
        -NodeKind 'recipe' `
        -Label $recipe.Name `
        -SourceRef "exact-build:items.v1.json:recipe:$($recipe.Id)" `
        -HashInput $recipe
}
foreach ($technology in $technologyModels) {
    $nodeId = "technology:$($technology.Id)"
    Add-GraphNode `
        -NodeId $nodeId `
        -NodeKind 'technology' `
        -Label $technology.Name `
        -SourceRef "exact-build:world.v1.json:technology:$($technology.Id)" `
        -HashInput $technology
}

foreach ($recipe in $recipeModels) {
    $recipeNodeId = "recipe:$($recipe.Id)"
    Add-GraphEdge `
        -EdgeId "recipe-output:$($recipe.Id)" `
        -FromNodeId $recipeNodeId `
        -ToNodeId "item:$($recipe.OutputId)" `
        -RelationKind 'produces_item' `
        -Attributes ([ordered]@{ quantity = $recipe.OutputQuantity }) `
        -SourceRef "exact-build:items.v1.json:recipe:$($recipe.Id)"
    for ($index = 0; $index -lt $recipe.Ingredients.Count; $index++) {
        $ingredient = $recipe.Ingredients[$index]
        Add-GraphEdge `
            -EdgeId "recipe-ingredient:$($recipe.Id):$index" `
            -FromNodeId "item:$($ingredient.ItemId)" `
            -ToNodeId $recipeNodeId `
            -RelationKind 'ingredient_for' `
            -Attributes ([ordered]@{ quantity = $ingredient.Quantity }) `
            -SourceRef "exact-build:items.v1.json:recipe:$($recipe.Id)"
    }
}
foreach ($technology in $technologyModels) {
    $technologyNodeId = "technology:$($technology.Id)"
    foreach ($itemId in $technology.UnlockItemIds) {
        Add-GraphEdge `
            -EdgeId "technology-unlock-item:$($technology.Id):$itemId" `
            -FromNodeId $technologyNodeId `
            -ToNodeId "item:$itemId" `
            -RelationKind 'unlocks' `
            -Attributes ([ordered]@{
                level = $technology.Level
                cost = $technology.Cost
            }) `
            -SourceRef "exact-build:world.v1.json:technology:$($technology.Id)"
    }
    foreach ($recipeId in $technology.UnlockRecipeIds) {
        Add-GraphEdge `
            -EdgeId "technology-unlock-recipe:$($technology.Id):$recipeId" `
            -FromNodeId $technologyNodeId `
            -ToNodeId "recipe:$recipeId" `
            -RelationKind 'unlocks' `
            -Attributes ([ordered]@{
                level = $technology.Level
                cost = $technology.Cost
            }) `
            -SourceRef "exact-build:world.v1.json:technology:$($technology.Id)"
    }
    if (
        -not [string]::IsNullOrWhiteSpace($technology.RequiredTechnologyId) -and
        $technologyById.ContainsKey($technology.RequiredTechnologyId)
    ) {
        Add-GraphEdge `
            -EdgeId (
                "technology-requires:$($technology.Id):" +
                $technology.RequiredTechnologyId
            ) `
            -FromNodeId $technologyNodeId `
            -ToNodeId "technology:$($technology.RequiredTechnologyId)" `
            -RelationKind 'requires' `
            -Attributes ([ordered]@{}) `
            -SourceRef "exact-build:world.v1.json:technology:$($technology.Id)"
    }
}

foreach ($item in $itemModels) {
    $weight = [Math]::Round($item.WeightMilli / 1000.0, 3)
    $body = @(
        "# $($item.Name)",
        '',
        '검증된 게임 빌드의 공개 허용 구조 데이터입니다.',
        '',
        "- 희귀도: $($item.Rarity)",
        "- 최대 묶음 수량: $($item.Stack)",
        "- 무게: $weight",
        "- 데이터 등급: $($item.Rank)"
    ) -join "`n"
    Add-WikiPage `
        -EntityNodeId "item:$($item.Id)" `
        -PageKind 'entity' `
        -Title $item.Name `
        -Summary '희귀도·무게·보유 한도를 확인한 공개 구조 데이터입니다.' `
        -Body $body `
        -Claim (
            "$($item.Name)의 희귀도, 무게, 최대 묶음 수량은 " +
            "게임 빌드 $GameBuildId 원본 표에서 확인했습니다."
        ) `
        -SourceRef "exact-build:items.v1.json:item:$($item.Id)"
}
foreach ($recipe in $recipeModels) {
    $ingredientLines = @(
        $recipe.Ingredients |
            ForEach-Object { "- $($_.Name): $($_.Quantity)개" }
    )
    $body = @(
        "# $($recipe.Name)",
        '',
        "결과: $($recipe.OutputName) $($recipe.OutputQuantity)개",
        "필요 작업량: $($recipe.WorkAmount)",
        '',
        '## 재료',
        '',
        ($ingredientLines -join "`n")
    ) -join "`n"
    Add-WikiPage `
        -EntityNodeId "recipe:$($recipe.Id)" `
        -PageKind 'guide' `
        -Title $recipe.Name `
        -Summary '결과 수량·필요 재료·작업량을 확인한 제작 구조입니다.' `
        -Body $body `
        -Claim (
            "$($recipe.Name)의 결과 수량, 재료 수량, 작업량은 " +
            "게임 빌드 $GameBuildId 원본 표에서 확인했습니다."
        ) `
        -SourceRef "exact-build:items.v1.json:recipe:$($recipe.Id)"
}
foreach ($technology in $technologyModels) {
    $unlockNames = New-Object Collections.Generic.List[string]
    foreach ($itemId in $technology.UnlockItemIds) {
        $unlockNames.Add($itemById[$itemId].Name)
    }
    foreach ($recipeId in $technology.UnlockRecipeIds) {
        $unlockNames.Add($recipeById[$recipeId].Name)
    }
    $bossLabel = if ($technology.IsBoss) { '예' } else { '아니요' }
    $bodyLines = @(
        "# $($technology.Name)",
        '',
        '검증된 게임 빌드의 기술 해금 구조입니다.',
        '',
        "- 해금 레벨: $($technology.Level)",
        "- 필요 기술 포인트: $($technology.Cost)",
        "- 보스 기술: $bossLabel"
    )
    if ($unlockNames.Count -gt 0) {
        $bodyLines += @('', '## 해금 항목', '')
        $bodyLines += @($unlockNames | Sort-Object -Unique |
            ForEach-Object { "- $_" })
    }
    Add-WikiPage `
        -EntityNodeId "technology:$($technology.Id)" `
        -PageKind 'entity' `
        -Title $technology.Name `
        -Summary '해금 레벨·필요 기술 포인트·연결 항목을 확인한 기술 데이터입니다.' `
        -Body ($bodyLines -join "`n") `
        -Claim (
            "$($technology.Name)의 해금 레벨과 필요 기술 포인트는 " +
            "게임 빌드 $GameBuildId 원본 표에서 확인했습니다."
        ) `
        -SourceRef (
            "exact-build:world.v1.json:technology:$($technology.Id)"
        )
}

if (
    $nodeStatements.Count -ne $graphNodeCount -or
    $edgeStatements.Count -ne $graphEdgeCount -or
    $pageStatements.Count -ne $pageCount -or
    $claimStatements.Count -ne $pageCount -or
    $revisionStatements.Count -ne $pageCount
) {
    throw (
        "Compiler count mismatch: nodes $($nodeStatements.Count)/" +
        "$graphNodeCount, edges $($edgeStatements.Count)/$graphEdgeCount, " +
        "pages $($pageStatements.Count)/$pageCount."
    )
}

New-Item -ItemType Directory -Path $resolvedOutput | Out-Null
$writtenSql = New-Object Collections.Generic.List[string]
$sqlFileRecords = New-Object Collections.Generic.List[object]
$datasetStatement = (
    "INSERT INTO data_versions " +
    "(dataset_version, game_version, game_build_id, schema_version, " +
    "source_hash, dataset_scope, verified, activated_at) VALUES (" +
    "$datasetSql, $(ConvertTo-SqlText $GameVersion), " +
    "$(ConvertTo-SqlText $GameBuildId), " +
    "$(ConvertTo-SqlText $schemaVersion), $manifestSql, " +
    "'public_metadata', 0, NULL);"
)
$datasetFile = '0000_dataset.sql'
Write-SeedSqlFile `
    -Name $datasetFile `
    -Statements @($datasetStatement) `
    -BaseRowsWrittenUpperBound 1
[void](Write-SqlChunks '0100_nodes' $nodeStatements 1)
[void](Write-SqlChunks '0200_edges' $edgeStatements 1)
[void](Write-SqlChunks '0300_pages' $pageStatements 2)
[void](Write-SqlChunks '0400_claims' $claimStatements 1)
[void](Write-SqlChunks '0500_revisions' $revisionStatements 1)

$opsStatements = New-Object Collections.Generic.List[string]
$opsStatements.Add(
    "INSERT INTO knowledge_dataset_manifests " +
    "(dataset_version, manifest_sha256, compiler_version, " +
    "graph_schema_version, wiki_schema_version, publication_status, " +
    "source_artifact_count, graph_node_count, graph_edge_count, " +
    "wiki_page_count) VALUES (" +
    "$datasetSql, $manifestSql, $(ConvertTo-SqlText $compilerVersion), " +
    "'property-graph-v1', 'compiled-wiki-v1', 'candidate', " +
    "$($sourceArtifacts.Count), $graphNodeCount, $graphEdgeCount, $pageCount);"
)
foreach ($artifact in $sourceArtifacts) {
    $opsStatements.Add(
        "INSERT INTO knowledge_source_artifacts " +
        "(dataset_version, artifact_id, artifact_kind, logical_source_ref, " +
        "sha256, byte_size, evidence_quality) VALUES (" +
        "$datasetSql, $(ConvertTo-SqlText $artifact.artifact_id), " +
        "$(ConvertTo-SqlText $artifact.artifact_kind), " +
        "$(ConvertTo-SqlText $artifact.logical_source_ref), " +
        "$(ConvertTo-SqlText $artifact.sha256), $($artifact.byte_size), 'exact');"
    )
}
$runId = "public-metadata-compile:$DatasetVersion"
$inputFacets = ConvertTo-CompactJson ([ordered]@{
    artifact_count = $sourceArtifacts.Count
    dataset_scope = 'public_metadata'
    game_artwork = 'excluded'
    game_descriptions = 'excluded'
})
$outputFacets = ConvertTo-CompactJson ([ordered]@{
    graph_schema = 'property-graph-v1'
    wiki_schema = 'compiled-wiki-v1'
    graph_nodes = $graphNodeCount
    graph_edges = $graphEdgeCount
    wiki_pages = $pageCount
})
$opsStatements.Add(
    "INSERT INTO knowledge_pipeline_runs " +
    "(run_id, dataset_version, pipeline_name, compiler_version, status, " +
    "input_facets_json, output_facets_json, completed_at) VALUES (" +
    "$(ConvertTo-SqlText $runId), $datasetSql, " +
    "'rights-safe-public-metadata-compilation', " +
    "$(ConvertTo-SqlText $compilerVersion), 'completed', " +
    "$(ConvertTo-SqlText $inputFacets), " +
    "$(ConvertTo-SqlText $outputFacets), CURRENT_TIMESTAMP);"
)
foreach ($artifact in $sourceArtifacts) {
    foreach ($output in @(
        @('graph', 'exact_projection'),
        @('wiki', 'wiki_compilation'),
        @('search_index', 'fts_indexing')
    )) {
        $lineageId = "lineage:$($artifact.artifact_id):$($output[0])"
        $opsStatements.Add(
            "INSERT INTO knowledge_lineage_edges " +
            "(dataset_version, lineage_id, run_id, input_artifact_id, " +
            "output_kind, output_id, transform_kind) VALUES (" +
            "$datasetSql, $(ConvertTo-SqlText $lineageId), " +
            "$(ConvertTo-SqlText $runId), " +
            "$(ConvertTo-SqlText $artifact.artifact_id), " +
            "$(ConvertTo-SqlText $output[0]), " +
            "$(ConvertTo-SqlText "$($output[0]):$DatasetVersion"), " +
            "$(ConvertTo-SqlText $output[1]));"
        )
    }
}
$opsStatements.Add(
    "INSERT INTO knowledge_wiki_links " +
    "(dataset_version, from_page_id, to_page_id, relation_kind, " +
    "source_edge_id) " +
    "SELECT edge.dataset_version, 'wiki:' || edge.from_node_id, " +
    "'wiki:' || edge.to_node_id, edge.relation_kind, edge.edge_id " +
    "FROM knowledge_graph_edges edge " +
    "JOIN knowledge_wiki_pages source_page " +
    "ON source_page.dataset_version=edge.dataset_version " +
    "AND source_page.page_id='wiki:' || edge.from_node_id " +
    "JOIN knowledge_wiki_pages target_page " +
    "ON target_page.dataset_version=edge.dataset_version " +
    "AND target_page.page_id='wiki:' || edge.to_node_id " +
    "WHERE edge.dataset_version=$datasetSql " +
    "AND edge.relation_kind <> 'references';"
)
$opsFile = '0600_operations.sql'
Write-SeedSqlFile `
    -Name $opsFile `
    -Statements @($opsStatements) `
    -BaseRowsWrittenUpperBound ($graphEdgeCount + 10)

$validateStatement = (
    "UPDATE knowledge_dataset_manifests SET publication_status='validated', " +
    "validated_at=CURRENT_TIMESTAMP WHERE dataset_version=$datasetSql " +
    "AND publication_status='candidate' " +
    "AND source_artifact_count=$($sourceArtifacts.Count) " +
    "AND graph_node_count=$graphNodeCount " +
    "AND graph_edge_count=$graphEdgeCount " +
    "AND wiki_page_count=$pageCount " +
    "AND (SELECT COUNT(*) FROM knowledge_source_artifacts " +
    "WHERE dataset_version=$datasetSql)=$($sourceArtifacts.Count) " +
    "AND (SELECT COUNT(*) FROM knowledge_graph_nodes " +
    "WHERE dataset_version=$datasetSql)=$graphNodeCount " +
    "AND (SELECT COUNT(*) FROM knowledge_graph_edges " +
    "WHERE dataset_version=$datasetSql)=$graphEdgeCount " +
    "AND (SELECT COUNT(*) FROM knowledge_wiki_pages " +
    "WHERE dataset_version=$datasetSql AND review_status='reviewed')=$pageCount " +
    "AND (SELECT COUNT(*) FROM knowledge_wiki_claims " +
    "WHERE dataset_version=$datasetSql)=$pageCount " +
    "AND (SELECT COUNT(*) FROM knowledge_wiki_revisions " +
    "WHERE dataset_version=$datasetSql AND review_status='reviewed')=$pageCount " +
    "AND NOT EXISTS (SELECT 1 FROM knowledge_error_book " +
    "WHERE dataset_version=$datasetSql AND status IN ('open','accepted'));"
)
$validateFile = '0900_validate_candidate.sql'
Write-SeedSqlFile `
    -Name $validateFile `
    -Statements @($validateStatement) `
    -BaseRowsWrittenUpperBound 1

$promotionStatements = @(
    "UPDATE data_versions SET activated_at=NULL " +
    "WHERE dataset_scope='public_metadata' AND verified=1 " +
    "AND activated_at IS NOT NULL AND dataset_version<>$datasetSql;",
    "UPDATE data_versions SET verified=1, activated_at=CURRENT_TIMESTAMP " +
    "WHERE dataset_version=$datasetSql AND dataset_scope='public_metadata' " +
    "AND verified=0 AND activated_at IS NULL " +
    "AND source_hash=$manifestSql " +
    "AND EXISTS (SELECT 1 FROM knowledge_dataset_manifests manifest " +
    "WHERE manifest.dataset_version=data_versions.dataset_version " +
    "AND manifest.manifest_sha256=$manifestSql " +
    "AND manifest.publication_status='validated' " +
    "AND manifest.source_artifact_count=$($sourceArtifacts.Count) " +
    "AND manifest.graph_node_count=$graphNodeCount " +
    "AND manifest.graph_edge_count=$graphEdgeCount " +
    "AND manifest.wiki_page_count=$pageCount) " +
    "AND NOT EXISTS (SELECT 1 FROM knowledge_error_book errors " +
    "WHERE errors.dataset_version=data_versions.dataset_version " +
    "AND errors.status IN ('open','accepted'));"
)
$promotionFile = 'OPERATOR_PROMOTE_AFTER_REVIEW.sql'
Write-Utf8File `
    -Path (Join-Path $resolvedOutput $promotionFile) `
    -Content (New-SqlDocument $promotionStatements)

$fileRecords = @(
    $sqlFileRecords |
        ForEach-Object {
            $path = Join-Path $resolvedOutput $_.path
            [ordered]@{
                path = $_.path
                sha256 = Get-FileSha256 $path
                payload_sha256 = $_.payload_sha256
                bytes = (Get-Item -LiteralPath $path).Length
                apply_order = $_.apply_order
                base_rows_written_upper_bound = (
                    $_.base_rows_written_upper_bound
                )
                conservative_rows_written = $_.conservative_rows_written
            }
        }
)
$promotionPath = Join-Path $resolvedOutput $promotionFile
$baseRowsWrittenUpperBound = [long](
    ($sqlFileRecords | Measure-Object `
        -Property base_rows_written_upper_bound -Sum).Sum
)
$conservativeRowsWritten = [long](
    ($sqlFileRecords | Measure-Object `
        -Property conservative_rows_written -Sum).Sum
)
$manifest = [ordered]@{
    schema = 'pal-public-knowledge-seed-v2'
    projection_sha256 = $projectionSha256
    compiler_version = $compilerVersion
    dataset_version = $DatasetVersion
    game_version = $GameVersion
    game_build_id = $GameBuildId
    dataset_scope = 'public_metadata'
    verified_candidate = $true
    automatic_activation = $false
    public_content_policy = $projectionIdentity.policy
    source_artifacts = $sourceArtifacts
    counts = $projectionIdentity.counts
    publish_strategy = [ordered]@{
        schema = 'resumable-prefix-v1'
        checkpoint_pipeline_name = 'public-metadata-seed-checkpoint-v1'
        checkpoint_base_rows_per_file = 2
    }
    d1_cost_projection = [ordered]@{
        model = 'resumable-file-upper-bound-x3-v1'
        base_rows_written_upper_bound = $baseRowsWrittenUpperBound
        conservative_rows_written = $conservativeRowsWritten
        note = (
            'Planning guard only; Cloudflare billing analytics remain ' +
            'authoritative after execution.'
        )
    }
    sql_files = $fileRecords
    operator_promotion = [ordered]@{
        path = $promotionFile
        sha256 = Get-FileSha256 $promotionPath
        bytes = (Get-Item -LiteralPath $promotionPath).Length
        requires_post_seed_review = $true
    }
}
$manifestPath = Join-Path $resolvedOutput 'seed-manifest.json'
Write-Utf8File `
    -Path $manifestPath `
    -Content ((ConvertTo-Json $manifest -Depth 30) + "`n")

Write-Output ([pscustomobject]@{
    output_directory = $resolvedOutput
    projection_sha256 = $projectionSha256
    items = $itemModels.Count
    recipes = $recipeModels.Count
    technologies = $technologyModels.Count
    graph_nodes = $graphNodeCount
    graph_edges = $graphEdgeCount
    wiki_pages = $pageCount
    sql_files = $writtenSql.Count
    automatic_activation = $false
})
